import json
import re
import os

porta = 7777


def createIndexPage():
    preHTML = """
        <!DOCTYPE html>
        <html lang="pt-PT">
        <head>
            <title> Cidades </title>
            <meta charset="UTF-8">
            <meta nome="viewport" content="width=device-width, initial-scale=1" >
            <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-light grey">
                    <h1> Cidades </h1>
                    <div class="list">
                    </header>
            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
    """

    posHTML = """
                    </ul>
                </div>
                <footer class="w3-container w3-light grey">
                    <h5>Generated by CidadesDeBraga::EngWeb2024::A95458</h5>                </footer>
            </div>
        </body>
    </html>
    """
    
    
    
    indexhtml = ""
    with open('mapa-virtual.json', 'r') as file:
        parsed_data = json.load(file)
        
    # Sort the cities alphabetically by name
    sorted_cities = sorted(parsed_data['cidades'], key=lambda x: x['nome'])

    for cidade in sorted_cities:
        indexhtml += f'<li><address><a href="http://localhost:7777/{cidade["id"]}">{cidade["nome"]}</a></address></li>'

    pagina_html = preHTML + indexhtml + posHTML

    with open("html/index.html", "w", encoding="UTF-8") as output_file:
        output_file.write(pagina_html)



def createCidadePage():
    with open('mapa-virtual.json', 'r') as file:
        parsed_data = json.load(file)

    for cidade in parsed_data['cidades']:
        html = """
            <!DOCTYPE html>
            <html lang="pt-PT">
            <head>
            <meta charset="UTF-8">
            <meta nome="viewport" content="width=device-width, initial-scale=1" >
            <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
            
    
    """

        html += f'<title>{cidade["nome"]}</title>'
        html += f'</head><body>'
        html += f'<h1>{cidade["nome"]}</h1>'
        html += f'<br>'
        html += f'<h4>População: {cidade["população"]}</h4>'
        html += f'<br>'
        html += f'<div class="text"><h4>Descrição: {cidade["descrição"]}</h4></div>'
        html += f'<br>'
        html += f'<h4>Distrito: {cidade["distrito"]}</h4>'
        html += "<br>"
        html += f'<b>Ligações a partir de {cidade["nome"]}:</b>'
        html += f'<div class="list"><ul>'

        for ligacao in parsed_data['ligacoes']:
            if ligacao["origem"] == cidade["id"]:
                for cid in parsed_data['cidades']:
                    if cid["id"] == ligacao["destino"]:
                        html += f'<li><adress><a href="http://localhost:7777/{cid["id"]}">{cid["nome"]}</a></address></li>'
        
        
        html += '</ul><address> <a href="http://localhost:7777/">Voltar à página principal</a> </address></div><div class="animation"></div></body></html>'

        output_filename = f'{cidade["id"]}.html'
        output_file_path = os.path.join(output_directory, output_filename)
        
        with open(output_file_path, "w", encoding="UTF-8") as output_file:
            output_file.write(html)

output_directory = './html'
createIndexPage()
    
createCidadePage()
