exports.mainPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Compositores</h1>
                </header>
                <div class="w3-container">
                    <p>HOME PAGE</p>
                </div>
                [<a class="w3-btn w3-round w3-teal" href="/compositores">Compositores</a>]
                [<a class="w3-btn w3-round w3-red" href="/periodos">Periodos</a>]
                <footer class="w3-container w3-blue">
                    <h5>Generated by JoaoGDFaria in ${d}</h5>
                </footer>
            </div>
        </body>
        `
}

exports.compositoresListPage = function(compositores, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th><th>Data Nascimento</th><th>Data Obito</th><th>Periodo</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < compositores.length ; i++){
        pagHTML += `
                <tr>    
                    <td>         
                        <a href="/compositores/${compositores[i].id}">
                            ${compositores[i].nome}
                        </a>
                    </td>
                    <td>${compositores[i].dataNasc}</td>
                    <td>${compositores[i].dataObito}</td>
                    <td>${compositores[i].periodo}</td>
                    <td>[<a class="w3-btn w3-round w3-teal" href="/compositores/edit/${compositores[i].id}">Edit</a>]
                    [<a class="w3-btn w3-round w3-red" href="/compositores/delete/${compositores[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-teal">
                    <h5>Generated by a95458 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// ---------------Student's Page--------------------------------
// Change and adapt to current dataset...
exports.compositorPage = function( comp, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${comp.Id}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${comp.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${comp.nome}</li>
                    <li><b>ID: </b> ${comp.id}</li>
                    <div class="w3-container">
                        <p><b>Data de Nascimento: </b>${comp.dataNasc}</p>
                        <p><b>Data de Óbito: </b>${comp.dataObito}</p>
                        <p><b>Período: </b>${comp.periodo}</p>
                        <p><b>Bio: </b>${comp.bio}</p>
                    </div>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
           </ul></div>
            <footer class="w3-container w3-teal">
                <address>Gerado por a95458 em ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.compositorFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.compositorFormEditPage = function(comp, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${comp.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${comp.nome}"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" value="${comp.dataNasc}"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito" value="${comp.dataObito}"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${comp.periodo}"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${comp.bio}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by a95458 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.periodsListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th>
                            <th>Ações</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td><a href="/periodos/${slist[i].id}">
                    ${slist[i].id}
                    </a></td>
                    <td>[<a class="w3-btn w3-round w3-teal" href="/periodos/edit/${slist[i].id}">Edit</a>]
                    [<a class="w3-btn w3-round w3-red" href="/periodos/delete/${slist[i].id}">Delete</a>]
                    </td>
                    
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by a95458 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodPage = function( period, d ){
    pagHTML =`
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Periodo ${period.id}</h1>
                </header>
                <div class="w3-container">
                    <h1><b>Nome:</b> ${period.id}</h1>
                </div>
                <ul class="w3-ul w3-hoverable">
                    <li class="w3-padding-16">
                    `
    for(let i=0; i < period.compositores.length ; i++){
        pagHTML += `
                    <li class="w3-padding-16">
                        ${period.compositores[i]}
                    </li>
        `
    }
    pagHTML += `
                </ul>
                <footer class="w3-container w3-blue">
                    <h5>Generated by a95458 in ${d} - [<a href="/compositores">Voltar</a>]</address> </h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <html>
    <head>
        <title>Error</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositores Erro</h1>
            </header>
            
            <p>${d}: Error: ${errorMessage}</p>

            <footer class="w3-container w3-teal">
                <address>Gerado por EngWeb2024 em ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
}